#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= board_i_dcm.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_bt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_camera.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_input.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= platform_i_dcm_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= gpiomux_i_dcm.o
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)	+= devices_i_dcm.o
