#platform-bsp@lge.com	2011.01
EXTRA_CFLAGS += -Ilge/include
obj-$(CONFIG_LGE_BACKLIGHT_LM3530) += backlight_lm3530.o	#for tag
obj-$(CONFIG_LGE_BACKLIGHT_LM3528) += backlight_lm3528.o
obj-$(CONFIG_LGE_BACKLIGHT_LM3533) += backlight_lm3533.o	#for vu
obj-$(CONFIG_LGE_BACKLIGHT_LM3537) += backlight_lm3537.o

#for vu
obj-$(CONFIG_LGE_DISPLAY_MIPI_HITACHI_VIDEO_HD_PT) += lcd_mipi_hitachi.o lcd_mipi_hitachi_video_hd_pt.o

#added by mo2chunghan.lee@lge.com - Fusion2_JB_Tag-11/06/2012 --
#for tag
obj-$(CONFIG_LGE_DISPLAY_MIPI_LGIT_VIDEO_HD_PT) += lcd_mipi_lgit.o mipi_lgit_video_wvga_pt.o

#for ijb 
obj-$(CONFIG_LGE_DISPLAY_MIPI_LGIT_IJB_VIDEO_HD_PT) += lcd_mipi_ijb_lgit.o lcd_mipi_lgit_video_hd_pt.o
#---------------------------------------------------------------
