#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_325_BOARD)	+= board_lge_325.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= platform_lge_325_bt.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= platform_lge_325_camera.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= platform_lge_325_input.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= platform_lge_325_misc.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= platform_lge_325_panel.o
obj-$(CONFIG_MACH_LGE_325_BOARD_LGU)	+= platform_lge_325_lgu_snd.o
obj-$(CONFIG_MACH_LGE_325_BOARD_SKT)	+= platform_lge_325_skt_snd.o
obj-$(CONFIG_MACH_LGE_325_BOARD_DCM)	+= platform_lge_325_snd.o
obj-$(CONFIG_MACH_LGE_325_BOARD_VZW)	+= platform_lge_325_vzw_snd.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= gpiomux_lge_325.o
obj-$(CONFIG_MACH_LGE_325_BOARD)	+= devices_lge_325.o
