#
# Makefile for the LGE platform device drivers.
#
#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_LGE_BROADCAST_DCM)	+= broadcast/
obj-y += camera/
obj-y += input/
obj-y += misc/
#obj-y += power/
obj-y += display/
obj-y += audio/
obj-y += mhl_v1/
obj-y += felica/
obj-y += device_lge.o
