#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
obj-$(CONFIG_LGE_BROADCAST_DCM)		+= radio-mb86a35/

# obj-$(CONFIG_LGE_BROADCAST_1SEG)		+= fc8101/
#for tag - added by mo2chunghan.lee@lge.com, 11/13/2012 --
obj-$(CONFIG_LGE_BROADCAST_ONESEG)      += fc8101/

