#
# Makefile for the ISDB-T FC8101 drivers.
#

# Each configuration option enables a list of files.
# LGE

obj-y		+= bbm.o
obj-y		+= fc8101.o
obj-y		+= fc8101_bb.o
obj-y		+= fc8101_hpi.o
obj-y		+= fc8101_isr.o
obj-y		+= fc8101_ppi.o
obj-y		+= fc8101_spi.o
obj-y		+= fc8101_tun.o
obj-y		+= fci_hal.o
obj-y		+= fci_i2c.o
obj-y		+= fci_oal.o
obj-y		+= fci_ringbuffer.o
obj-y		+= fci_tun.o